Add `dynexec` assembly instruction, tests, and docs
0xPolygonMiden/miden-vm pull request #1078
Opened 2023-09-27 13:45 UTC by grjte

This PR addresses part of #728, and exposes the new dynamic node capabilities to the user via the new `dynexec` instruction.

- [x] add `dynexec` instruction
- [x] add tests
- [x] add docs

2023-09-29 05:22 UTC, bobbinth requested changes
Looks good! Thank you! I left a few comments inline - the only blocking one, is the one about docs.

2023-09-29 05:22 UTC, bobbinth commented on miden/tests/integration/flow_control/mod.rs
> +        end";
minor nit: `drop drop drop drop` can be replaced with `dropw` and `push.0 push.0 push.0 push.0` can be replaced with `padw`.

But also, now seeing this I wonder if there is a way to drop the procedure hash from the stack automatically. The main reason for this is that without the automatic drop, the implementation of `foo` becomes "context-specific". That is, the way we'd invoke it using `exec` or `call` instructions must be different from the way we invoke it using `dynexec` or `dyncall` instructions (i.e. in the first case we need to pad the stack, and in the second case we don't).

I'm not sure how to do this though (or even if it is possible, given our structure) - so, unless you see some simple solution to this, it should probably be left to future work (and then let's create an issue for this).

2023-09-29 05:22 UTC, bobbinth commented on miden/tests/integration/flow_control/mod.rs
> +        end";
A separate comment: I wonder how much effort it is to do this test "more properly." That is, instead of populating `cb_table` via the `call` instruction, populate it manually by first compiling `foo` and then adding it to the `cb_table` of the actual program. If this is not too complicated, might be good to change the test to work like that - but also, I don't think this is a blocking issue.

2023-09-29 18:50 UTC, bitwalker commented on miden/tests/integration/flow_control/mod.rs
> +        end";
> But also, now seeing this I wonder if there is a way to drop the procedure hash from the stack automatically. The main reason for this is that without the automatic drop, the implementation of foo becomes "context-specific". 

It'd definitely be best if dropping it was part of the `dynexec`/`dyncall` semantics. That said, there is a pretty simple workaround, by using compiler-generated wrapper functions, e.g:

```masm
proc.foo
  ...
end

proc.foo_dyn
  dropw
  exec.foo
end

begin
  # assume the hash for foo_dyn is on the stack
  dynexec
end
```

It's not ideal, but is at least feasible. Another option would be to make padding the stack part of the calling convention of all functions, so that whether a function is invoked via `exec` or `dynexec`, the callee can assume there is a word on the stack to be dropped.

@bobbinth you mentioned on our call today that automatically dropping the hash would be tricky to implement; I feel like I don't have a good grasp on what dictates whether something like this is simple or complex/impossible. Put another way, most instructions have some kind of stack manipulation implicit in their semantics (e.g. `assert` drops its operand, while `u32.assert` does not). I guess it's not clear to me why `dynexec`/`dyncall` would be different in this regard. If you have any good recommendations on how I can build up some better intuition around that sort of thing, I'd definitely be interested.

2023-10-03 01:35 UTC, bobbinth commented on miden/tests/integration/flow_control/mod.rs
> +        end";
The main issue here is that we can change stack depth by at most 1 per VM cycle. This limitation is due to how the constraint system for the operand stack works. The constraints are described [here](https://0xpolygonmiden.github.io/miden-vm/design/stack/main.html), though this article assumes a fairly deep understanding of AIR constraints in general.

So, any assembly instruction which changes stack depth by more than 1 needs to be emulated by multiple VM operations. For example, `dropw` is basically just a shorthand for `drop drop drop drop`.

The problem with dynamic calls is that we cannot apply the above technique. The stack needs to contain the hash of the dynamic procedure at the time `DYN` operation is executed by the VM. This means, we cannot drop the hash and then execute `DYN`. Thus, the drop operations must be a part of the procedure referred to by `DYN`.

One potential way to get around this is to change the semantics of the `DYN` operation to work as follows:
- Instead of providing the hash of the procedure via the stack, we provide the memory address which contains the hash of the procedure.
- `DYN` operation then gets the hash from that memory address, drops the address from the stack, and starts executing the dynamic procedure.

Stack transition for `DYN` operation would look as follows:
```
Inputs:  [proc_ptr, ...]
Outputs: [...]
```
Where `proc_ptr` is memory address containing the hash of the procedure to be executed.

Instead of the current:
```
Inputs:  [PROC_HASH, ...]
Outputs: [PROC_HASH, ...]
```
Where `PROC_HASH` is a word containing the hash of the procedure to be executed.

Switching to this new approach does mean that we'd need to perform a memory read when we execute a `DYN` operation - and so, we should take this into account when refactoring the memory subsystem. But this is a viable approach and I think having procedure hash come from memory may be a good thing anyway.

2023-10-03 04:01 UTC, bitwalker commented on miden/tests/integration/flow_control/mod.rs
> +        end";
I see, that makes sense.

> The constraints are described [here](https://0xpolygonmiden.github.io/miden-vm/design/stack/main.html), though this article assumes a fairly deep understanding of AIR constraints in general.

Yeah I think at some point I'm going to have to get into the gritty details of that stuff to better formulate proposals/suggestions around some of these features we're discussing. I just know it's going to be a slog, so I've been putting it off 😅 

> One potential way to get around this is to change the semantics of the DYN operation to work as follows:
>
> * Instead of providing the hash of the procedure via the stack, we provide the memory address which contains the hash of the procedure.
> * DYN operation then gets the hash from that memory address, drops the address from the stack, and starts executing the dynamic procedure.

I think this probably works better in practice for the compiler anyway, since the set of functions we'd use `dynexec` with would generally be known statically (we just wouldn't know exactly which function is called, since it's indirect), so we could place the hashes in a table in memory and just reference them as needed. I do think this is another example of where having some way to provide statically initialized, read-only data (i.e. akin to the `rodata` section of an ELF executable) as part of the program data would be ideal. Having the callee be referenced via hash is certainly better than a raw pointer like on other architectures, but someone could still replace the hash stored in memory with a different one of their choosing (harder to pull that kind of thing off with the operand stack).

In any case, +1 from me - but I do think we should at least keep our eye on some way to lock-down regions of memory that are intended to be read-only, so as to prevent both intentional and unintentional writes to those regions from causing unexpected behavior, or worse. It certainly remains to be seen in what ways stuff like that could be exploited in practice, but there are other benefits to being able to mark memory read-only (in particular, it makes identifying the source of memory corruption due to incorrectly constructed/modified pointers much easier). That said, I have no idea how doable that is, so might have to be something we punt further into the future.

2023-10-03 18:49 UTC, bobbinth approved these changes
All looks good! Thank you!

Let's resolve the merge conflict and merge.

2023-10-04 21:38 UTC, merged