Ask clippy for automatic fixes
0xPolygonMiden/miden-vm pull request #613
Opened 2023-01-04 08:46 UTC by matthiasgoergens

As part of CI/CD we are running

```
cargo clippy --all -- -D clippy::all -D warnings
```

Inspired by that, we can ask clippy to also suggest a few additional fixes:

```
cargo clippy --all --fix --allow-dirty -- -D clippy::all -D warnings
```

Most changes are quite trivial (but make the code a bit cleaner), but have a look at `miden/tests/integration/stdlib/math/ecgfp5/group.rs` for the one non-trivial refactor.

2023-01-04 08:56 UTC, matthiasgoergens commented
P.S. In general there's lots more interesting small improvements we can get out of clippy almost for 'free'.

2023-01-05 21:11 UTC, grjte requested changes
Thank you for this! As expected of clippy, all of these changes look good, and there are some nice readability improvements in addition to larger cleanups like the one you pointed out. I also agree with you about `pedantic` often giving good improvements for free.

However, as convenient as it would be to automate these improvements a bit more, I think we'd prefer not to have code getting modified during the CI run. So I think we'll keep the CI run as it is instead of adding the `--fix` flag, and for now continue leaving it to people to run clippy locally.

It looks like you didn't actually make that change to the CI run here and this is just the clippy fixes, so would you mind updating the commit info so the log more accurately describes this change? After that, I'm happy to merge.

2023-01-06 07:36 UTC, matthiasgoergens commented
@grjte I realise that my description was a bit confusing.  Yes, I did not mean to run `--fix` automatically, I just meant that my suggestions here come from `--fix` (with one small change: `--fix` wanted to introduce trailing whitespace for some reason..)

2023-01-06 11:15 UTC, grjte approved these changes
Thanks for clarifying, looks good!

2023-01-06 11:16 UTC, merged