remame vm native hash fnc nomenclature
0xPolygonMiden/miden-vm pull request #684
Opened 2023-02-07 09:05 UTC by 0xKanekiKen

Signed-off-by: 0xKanekiKen <100861945+0xKanekiKen@users.noreply.github.com>

## Describe your changes
This PR addresses #590. 

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

2023-02-07 14:20 UTC, grjte requested changes
Thanks @0xKanekiKen! Looks good to me, except for one typo

2023-02-07 14:20 UTC, grjte commented on air/src/stack/op_flags/mod.rs
> +    /// Operation Flag of HMPERM operation.
nit: typo in `HPerm`

2023-02-08 08:27 UTC, itzmeanjan approved these changes
Looks good.

2023-02-09 06:52 UTC, bobbinth commented
@0xKanekiKen - it seems like this does not fully address #590 yet (the `hash` instruction is not added). Is the plan to add it in a different PR?

2023-02-09 10:18 UTC, grjte commented
> @0xKanekiKen - it seems like this does not fully address #590 yet (the `hash` instruction is not added). Is the plan to add it in a different PR?

I think it makes sense to handle the renaming in this PR and add `hash` in another one, unless you object to that

2023-02-09 10:28 UTC, grjte approved these changes
This looks good to me for the renaming of `hperm` and `hmerge`. As mentioned by @bobbinth, the remaining item from #590 is to add the `hash` instruction. 

That task is described as requiring migration of `rescue_prime::hash_1to1` from the standard library into the assembly operations and renaming it to `hash`. However, the PR for adding that hash function to the stdlib (#576) is still pending, so it makes sense to tackle this separately (and perhaps just change the outstanding PR)

2023-02-09 15:39 UTC, 0xKanekiKen commented
Thanks @grjte for mentioning it. I was waiting for an update on the PR #576.

2023-02-10 05:51 UTC, merged