Refactor: move assertions to start of functions
0xPolygonMiden/miden-vm pull request #707
Opened 2023-02-20 19:33 UTC by MuhtasimTanmoy

## Describe your changes
This PR moves assertions to the start of functions. Resolves #537.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to the naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

2023-02-20 19:40 UTC, MuhtasimTanmoy commented
[Rustfmt](https://github.com/rust-lang/rustfmt) and [Clippy](https://github.com/rust-lang/rust-clippy) linting provided two change requests.

```
- assert_eq!(expected, format!("{}", program));  // change this to the following
+ assert_eq!(expected, format!("{program}"));
```

And,

```
-  assert_eq!(expected, format!("{}", program));  // change this to the following
+  assert_eq!(expected, format!("{program}"));
```

Do I need to update those occurrences too?

2023-02-20 19:46 UTC, MuhtasimTanmoy commented
Should I change the numeric value in the following line to a `CONSTANT`  declared in [assembly/src/lib.rs](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/lib.rs)

```rust
assert_eq!(self.module_stack.len(), 1, "executable not last module. module_stack len should be 1");
```

to

```rust
assert_eq!(self.module_stack.len(), SOME_CONSTANT, "executable not last module. module_stack len should be 1");
```
this?

2023-02-23 01:08 UTC, vlopes11 requested changes
The changes looks good! We shouldn't close the issue yet because we need to check the other places as well.

However, the CI is breaking with `rustfmt`. Be sure to execute `cargo fmt` so it will pass on that test.

2023-02-23 01:08 UTC, vlopes11 commented on assembly/src/assembler/context.rs
>          assert!(main_proc_context.is_main(), "not main procedure");
I wonder if this shouldn't be a case to justify a signature change for the function...Usually, when we can't describe the assertion at the beginning of the function, then chances are we the function shouldn't be infallible.

But, sticking to the scope of the PR, the implementation is fine as it is!

2023-02-23 01:08 UTC, vlopes11 commented on assembly/src/assembler/context.rs
> -        assert!(self.proc_stack.is_empty(), "more procedures after main");
Good catch! If the length is asserted, then this check is redundant.

2023-02-23 06:31 UTC, MuhtasimTanmoy commented
> Be sure to execute cargo fmt so it will pass on that test.

Done.

2023-02-23 07:38 UTC, bobbinth requested changes
Thank you for working on this! I think it looks good - I left just a couple of nits inline. To answer your questions:

> Should I change the numeric value in the following line to a `CONSTANT` declared in [assembly/src/lib.rs](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/lib.rs)

I don't think this is needed.

> [Rustfmt](https://github.com/rust-lang/rustfmt) and [Clippy](https://github.com/rust-lang/rust-clippy) linting provided two change requests.
> ...
> Do I need to update those occurrences too?

Would be great, but not required.

2023-02-23 07:38 UTC, bobbinth commented on assembly/src/assembler/context.rs
> +    /// - If the procedure context is not main.
nit: I'd change these to:
```
- If this module is not an executable module.
- If there is not exactly one procedure left on the procedure stack.
- If the procedure left on the procedure stack is not main procedure.
```

2023-02-23 07:38 UTC, bobbinth commented on assembly/src/assembler/context.rs
> +            "procedure stack should only have the main procedure. proc_stack length should be 1"
nit: I'd change the message to: "procedure stack must contain exactly one procedure".

2023-02-23 07:38 UTC, bobbinth commented on assembly/src/assembler/context.rs
> +            "executable not last module. module_stack len should be 1"
nit: I'd change the message to: "module stack must contain exactly one module".

2023-02-23 10:35 UTC, MuhtasimTanmoy commented
Fix given as per feedback.

2023-02-23 15:53 UTC, bobbinth commented
@MuhtasimTanmoy - looks good! Could you fix the `rustfmt` issue and we can merge.

2023-02-23 16:41 UTC, bobbinth approved these changes

2023-02-23 16:42 UTC, MuhtasimTanmoy commented
> Could you fix the rustfmt issue and we can merge.

Done as suggested.

------

However, there is something that has left me perplexed which I would like to bring to your attention.

In our previous workflow run, `cargo fmt` suggested converting this line
```
assert_eq!(self.module_stack.len(), 1, "executable not last module. module_stack len should be 1");
```
to

```
assert_eq!(
            self.module_stack.len(),
            1,
            "module stack must contain exactly one module"
        );
```
So, as suggested, I performed this action in commit https://github.com/0xPolygonMiden/miden-vm/pull/707/commits/3639582e5d9e7c648231af38cfc2b1f893c5bea1, which eliminated all errors from the workflow check.


However, in our last workflow run, the error highlighted by "cargo fmt" suggested converting this line
```
assert_eq!(
            self.module_stack.len(),
            1,
            "module stack must contain exactly one module"
        );
```
back into
```
assert_eq!(self.module_stack.len(), 1, "executable not last module. module_stack len should be 1");
```

So, I reverted back to the previous structure in my last commit https://github.com/0xPolygonMiden/miden-vm/pull/707/commits/70bcf4abb47e6b5bde2cd7e2311cfc5dee87b814

I don't particularly get the reason for this.

2023-02-23 17:00 UTC, merged