Improve Assembly (De)Serialization
0xPolygonMiden/miden-vm pull request #825
Opened 2023-04-04 13:10 UTC by itzmeanjan

This PR addresses the issue described on https://github.com/0xPolygonMiden/miden-vm/issues/731.

- [x] Make Miden assembly serialization infallible
- [ ] Use Serializable/Deserializable traits defined in `winter-utils` ( more @ https://github.com/facebook/winterfell/blob/9b33ffe63ce48385349381f25341111376de19bd/utils/core/src/serde/mod.rs ) for reducing code duplication in `miden-assembly` ( more @ https://github.com/0xPolygonMiden/miden-vm/blob/4195475d75ab2d586bdb01d1ff3ea2cd626eaf7b/assembly/src/serde/mod.rs )

2023-04-04 23:05 UTC, bobbinth requested changes
Looks good! Thank you! I left a few small comment inline.

Main thing: we should remove generic serializers for strings and vectors and handle these serializations individually at their call sites.

2023-04-04 23:05 UTC, bobbinth commented on assembly/src/serde/mod.rs
>      }
i would remove this method as winterfell `Serializable` trait doesn't have it - and so, we'd need to remove it anyway.

The way to handle this is to handle string serialization at the call sites of this method.

2023-04-04 23:05 UTC, bobbinth commented on assembly/src/serde/mod.rs
>          self.pos += len;
Similar to the previous comment. I would remove this method.

2023-04-04 23:05 UTC, bobbinth commented on assembly/src/serde/mod.rs
>  }
I would remove these implementations. And also would remove implementations for serializing `Vec<T>` below.

2023-04-06 10:07 UTC, itzmeanjan commented
> Main thing: we should remove generic serializers for strings and vectors and handle these serializations individually at their call sites.

I make those changes in https://github.com/0xPolygonMiden/miden-vm/pull/825/commits/66523999f6631d2679548ea19fb63f2d82dedd4e. Now we're only dependent on `winter-utils` crate's (De)Serializable interfaces.

2023-04-06 10:08 UTC, itzmeanjan commented on assembly/src/library.rs
> +        target.write_u64(modules.len() as u64);
I use `u16` for encoding length of string for certain cases, though generally I stick to using `u64`. I hope I've not missed any.

2023-04-06 23:28 UTC, bobbinth requested changes
Looks good! Thank you! I left a bunch of small comments - primarily about switching length encodings from `u64` to `u16`. We should also create an issue to address the TODOs and make sure we enforce proper bounds on these at construction time.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/parsers/mod.rs
> +        self.body.write_into(target);
I think `u64` both for docs and for body length is too much - let's use `u16` and add TODOs to enforce these restrictions via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/parsers/mod.rs
> +        self.body.write_into(&mut target);
I think `u64` both for body length is too much - let's use `u16` and add a TODO to enforce this restriction via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/parsers/mod.rs
> +        target.write_u64(self.local_procs.len() as u64);
I think `u64` both for docs and for the number of procedures is too much - let's use `u16` and add TODOs to enforce these restrictions via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/parsers/serde/deserialization.rs
> +            let else_block = Deserializable::read_batch_from(source, else_block_len)?;
I think `u64` for number of nodes here and for other statements is too much - let's use `u16` and add TODOs to enforce these restrictions via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/parsers/serde/deserialization.rs
>              ])),
Would `source.read_array()?` work here instead?

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/library.rs
> +        target.write_u64(modules.len() as u64);
I'd use a `u16` here still and add a TODO to ensure this restriction via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/lib.rs
>      }
I think `u64` is too much - let's use `u16` and add TODOs to enforce this restriction via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/lib.rs
>      }
I think `u64` is too much - let's use `u16` and add TODOs to enforce this restriction via the constructor.

2023-04-06 23:28 UTC, bobbinth commented on assembly/src/lib.rs
>      }
I think `u64` is too much - let's use `u16` and add TODOs to enforce this restriction via the constructor.

2023-04-10 10:42 UTC, itzmeanjan commented on assembly/src/parsers/serde/deserialization.rs
>              ])),
I see `read_array` reads N ( compile-time defined ) bytes from source byte stream. More @ https://github.com/facebook/winterfell/blob/9b33ffe63ce48385349381f25341111376de19bd/utils/core/src/serde/byte_reader.rs#L155-L161

2023-04-10 11:14 UTC, itzmeanjan commented on assembly/Cargo.toml
> +winter-utils = { package = "winter-utils", version = "0.6", default-features = false }
> I think this is primarily used for serialization traits, right? If so, we can get these from [miden-core](https://github.com/0xPolygonMiden/miden-vm/blob/next/core/src/utils/mod.rs#L14) (they are re-exported there from `winter-utils`).

I address this issue in 0d14aa953fa785e1d0f253cf2fdf0bb8dfd5ae33

2023-04-10 11:14 UTC, itzmeanjan commented on assembly/src/procedures/mod.rs
>          Ok(name)
Addressed in c038d78fc458a9c5fc5b4fbf67df2513556d8b66

2023-04-10 11:27 UTC, itzmeanjan commented
> create an issue to address the TODOs

Created https://github.com/0xPolygonMiden/miden-vm/issues/836

2023-04-10 20:23 UTC, bobbinth approved these changes
Looks good! Thank you!

2023-04-10 20:24 UTC, merged