cli: add command to compile libraries
0xPolygonMiden/miden-vm pull request #997
Opened 2023-07-07 14:12 UTC by hackaugusto

## Describe your changes

This adds a CLI command to compile masm files to a masl, useful for CLI users.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

2023-07-07 14:19 UTC, hackaugusto commented on miden/src/cli/compile_lib.rs
> +}
I tried to reuse the `CompileCmd`, but `compile` is written to `compile` a whole program, which may use multiple libraries, each with their own namespace, i couldn't think of a simple/clear interface to do that.

2023-07-08 20:01 UTC, bobbinth requested changes
Looks good! Thank you! I left a few comments inline. The main thing is that I'm thinking we should change the command to work more like this:
```
miden bundle <dir> --version <version> --namespace <namespace>
```
Where `namespace` is optional.

2023-07-11 14:34 UTC, hackaugusto commented on miden/src/cli/compile_lib.rs
> +        let version = Version::try_from(env!("CARGO_PKG_VERSION")).expect("invalid cargo version");
added a CLI optional argument, set the default to `0.1`, let me know if it should instead be a required positional argument.

2023-07-11 14:36 UTC, hackaugusto commented on miden/src/cli/compile_lib.rs
> +pub struct CompileLibraryCmd {
changed.

2023-07-11 14:37 UTC, hackaugusto commented
> Looks good! Thank you! I left a few comments inline. The main thing is that I'm thinking we should change the command to work more like this:

This would force the user to have a different folder per bundle, that is a more constrained version of the command. For example, if there are two versions of the same library, and they share a `utils`, that design would require copying the code.

Should I change?

2023-07-17 08:05 UTC, bobbinth commented
> This would force the user to have a different folder per bundle, that is a more constrained version of the command. For example, if there are two versions of the same library, and they share a `utils`, that design would require copying the code.

Not sure I fully followed this: doesn't the command take all MASM files from a given directory? How would a shared directory be specified in this case? (and what namespace in the library hierarchy would it get?)

2023-07-17 08:42 UTC, hackaugusto commented
> Not sure I fully followed this: doesn't the command take all MASM files from a given directory? How would a shared directory be specified in this case? (and what namespace in the library hierarchy would it get?)

My mistake. I had something else in mind. I'm making the requested changes.

2023-07-18 03:41 UTC, bobbinth approved these changes
Looks good! Thank you! I added one commit which fixes a few typos in the docs.

2023-07-18 04:02 UTC, merged